# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 946e57096faa77be453d455fea60b409fdf51f94891bb49135dc3aa68e93faff78e2c3cbedf2df4b4c6662ebc6be296f27baabf6c1133079a1ea187036fd7cb2

test:
  secret_key_base: dc472940eba538d1e9f1baeea628583fb63e27a792e2a24410d90a7dfa75d077456db90eba342207b445a2ebc1ea62b8024a0cf57532027a01fadcafc142f138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
